# Generated by Django 4.2.21 on 2025-05-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200, unique=True)),
                ('price_range', models.CharField(choices=[('€', 'Budget'), ('€€', 'Moderate'), ('€€€', 'Expensive'), ('€€€€', 'Luxury')], max_length=4)),
                ('description', models.TextField()),
                ('opening_hours', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
