# Generated by Django 4.2.21 on 2025-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_from_zaragoza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to feature this restaurant'),
        ),
    ]
