# Generated by Django 4.2.21 on 2025-06-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='zaragoza_image',
        ),
    ]
